declare -g LINUXFAMILY=genio
declare -g OVERLAY_DIR="/boot/dtb/mediatek/overlay"
declare -g ARCH=arm64
declare -g GOVERNOR=performance
declare -g INSTALL_ARMBIAN_FIRMWARE=no
declare -g LINUXFAMILY="arm64"
declare -g ARCH="arm64"

declare -g UEFI_GRUB="skip" # Skip GRUB for this board

declare -g LINUXCONFIG="linux-genio-$BRANCH"

#Kernel Setup
declare -g BRANCH="collabora"
declare -g KERNEL_MAJOR_MINOR="6.14"                                			# Major and minor versions of this kernel.
declare -g KERNELPATCHDIR='genio-1200-collabora'                   				# Try to keep this as empty as possible. We won't work on top of Collabora's branch, they rebase all the time. New DTs are ok.
declare -g KERNELSOURCE='https://gitlab.collabora.com/mediatek/aiot/linux.git' 	# Directly from Collabora...
declare -g KERNELBRANCH='branch:mediatek-next'                     				# Rolling kernel branch, will be rebased
declare -g EXTRAWIFI="no"
declare -g INSTALL_HEADERS="yes"

# Enable extlinux and u-boot-menu
declare -g SRC_EXTLINUX="yes"
declare -g SRC_CMDLINE="loglevel=7 console=ttyS0,921600 root=LABEL=armbi_root rootwait rootfstype=ext4"
declare -g EXTLINUX_SPECIFIC_FDT="yes"
declare -g NAME_INITRD="uInitrd"
declare -g EXTLINUX_UINITRD="yes"

# Enable u-boot-menu extension
enable_extension "u-boot-menu"

# U-Boot menu configuration
declare -g U_BOOT_MENU_LABEL="Armbian Genio"
declare -g U_BOOT_TIMEOUT="3"
declare -g U_BOOT_PARAMETERS="${SRC_CMDLINE}"

# Use vmlinuz as kernel image type and install type so it can package the kernel image with the correct git commit hash suffix
declare -g KERNEL_IMAGE_TYPE="vmlinuz"
declare -g KERNEL_INSTALL_TYPE="install"
declare -g NAME_KERNEL="vmlinuz"
