# Qualcomm SA8775P
declare -g BOARD_NAME="Radxa Airbox Q900"
declare -g BOARD_VENDOR="radxa"
declare -g BOARD_MAINTAINER="HeyMeco"
declare -g BOARDFAMILY="sa8775p"
declare -g KERNEL_TARGET="qcom-linux"
declare -g BOOTCONFIG="none"
declare -g IMAGE_PARTITION_TABLE="gpt"
declare -g BOOT_FDT_FILE="qcom/qcs9075-radxa-airbox-q900.dtb"
declare -g BOARD_FIRMWARE_INSTALL="-full"
enable_extension "grub-with-dtb"
